name: Generate JSON Feeds

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Set up Python 3.11
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install Dependencies
      run: pip install -r requirements.txt --require-hashes --no-deps
    - name: Generate Feeds
      run: |
        # Generate the JSON Feeds
        python feed-me.py
    - name: Copy Generate Feeds
      run: |
        mkdir feed
        cp -R build/. static feed/
    - name: Upload Feeds as Artifacts
      uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa
      with:
        path: ./feed

  # Deployment job
  deploy:
    if: (github.event_name == 'push'
      && github.ref_name == 'main') || github.event_name == 'workflow_dispatch'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e
